version: '3'

services:
  api:
    build: ./
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    env_file:
      - ./.env.dev
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    ports:
      - "6360"
    container_name: rd01
  celery:
    build: .
    container_name: c01
    command: bash -c "
      cd code/slack_app
      && celery worker -A slack_app --loglevel=info
      "
    depends_on:
      - redis


volumes:
  postgres_data:
  redis: