# Generated by Django 2.2.6 on 2019-10-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NS', 'not started'), ('DOING', 'doing'), ('DONE', 'done')], max_length=12)),
                ('severity', models.CharField(choices=[('L', 'low'), ('M', 'medium'), ('H', 'high')], max_length=10)),
                ('reporter', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
